In [1]:
I decided to treat this as a classification problem by creating a new binary variable affair 
(did the woman have at least one affair?) and trying to predict the classification for each woman. 
 
Dataset 
 
The dataset I chose is the affairs dataset that comes with Statsmodels. 
It was derived from a survey of women in 1974 by Redbook magazine, 
in which married women were asked about their participation in extramarital affairs. 
More information about the study is available in a 1978 paper from the Journal of Political Economy. 
 
Description of Variables 
 
The dataset contains 6366 observations of 9 variables: 
 
rate_marriage: woman's rating of her marriage (1 = very poor, 5 = very good) 
 
age: woman's age 
 
yrs_married: number of years married 
 
children: number of children 
 
religious: woman's rating of how religious she is (1 = not religious, 4 = strongly religious) 
 
educ: level of education (9 = grade school, 12 = high school, 14 = some college, 16 = college graduate, 
                          17 = some graduate school, 20 = advanced degree) 

 
occupation: woman's occupation (1 = student, 2 = farming/semiskilled/unskilled, 3 = "white collar", 4 = teacher/nurse/writer/technician/skilled, 5 = managerial/business, 6 = professional with advanced degree) 
 
occupation_husb: husband's occupation (same coding as above) 
 
affairs: time spent in extra-marital affairs 

SyntaxError: invalid syntax (<ipython-input-1-bfb49d945396>, line 1)

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices

In [5]:
df = sm.datasets.fair.load_pandas().data 
df.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  
0              5.0  0.111111  
1              4.0  3.230769  
2              5.0  1.400000  
3              5.0  0.727273  
4              4.0  4.666666

In [6]:
df['affair'] = (df['affairs']>0).astype(int)

In [7]:
df.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  affair  
0              5.0  0.111111       1  
1              4.0  3.230769       1  
2              5.0  1.400000       1  
3              5.0  0.727273       1  
4              4.0  4.666666       1

In [8]:
y,X = dmatrices('affair~rate_marriage+age+yrs_married+children+religious+educ+C(occupation)+C(occupation_husb)',
                df,return_type="dataframe")

In [9]:
X

Intercept  C(occupation)[T.2.0]  C(occupation)[T.3.0]  \
0           1.0                   1.0                   0.0   
1           1.0                   0.0                   1.0   
2           1.0                   0.0                   1.0   
3           1.0                   0.0                   0.0   
4           1.0                   0.0                   1.0   
...         ...                   ...                   ...   
6361        1.0                   0.0                   0.0   
6362        1.0                   0.0                   0.0   
6363        1.0                   0.0                   1.0   
6364        1.0                   0.0                   1.0   
6365        1.0                   1.0                   0.0   

      C(occupation)[T.4.0]  C(occupation)[T.5.0]  C(occupation)[T.6.0]  \
0                      0.0                   0.0                   0.0   
1                      0.0                   0.0                   0.0   
2                      0.0                   0.0                   0.0   
3                      0.0                   1.0                   0.0   
4                      0.0                   0.0                   0.0   
...                    ...                   ...                   ...   
6361                   1.0                   0.0                   0.0   
6362                   0.0                   1.0                   0.0   
6363                   0.0                   0.0                   0.0   
6364                   0.0                   0.0                   0.0   
6365                   0.0                   0.0                   0.0   

      C(occupation_husb)[T.2.0]  C(occupation_husb)[T.3.0]  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   
...                         ...                        ...   
6361                        0.0                        1.0   
6362                        0.0                        0.0   
6363                        0.0                        0.0   
6364                        0.0                        0.0   
6365                        0.0                        0.0   

      C(occupation_husb)[T.4.0]  C(occupation_husb)[T.5.0]  \
0                           0.0                        1.0   
1                           1.0                        0.0   
2                           0.0                        1.0   
3                           0.0                        1.0   
4                           1.0                        0.0   
...                         ...                        ...   
6361                        0.0                        0.0   
6362                        0.0                        1.0   
6363                        0.0                        0.0   
6364                        1.0                        0.0   
6365                        1.0                        0.0   

      C(occupation_husb)[T.6.0]  rate_marriage   age  yrs_married  children  \
0                           0.0            3.0  32.0          9.0       3.0   
1                           0.0            3.0  27.0         13.0       3.0   
2                           0.0            4.0  22.0          2.5       0.0   
3                           0.0            4.0  37.0         16.5       4.0   
4                           0.0            5.0  27.0          9.0       1.0   
...                         ...            ...   ...          ...       ...   
6361                        0.0            5.0  32.0         13.0       2.0   
6362                        0.0            4.0  32.0         13.0       1.0   
6363                        0.0            5.0  22.0          2.5       0.0   
6364                        0.0            5.0  32.0          6.0       1.0   
6

In [10]:
X = X.rename(columns = {'C(occupation)[T.2.0]':'occ_2', 
 
'C(occupation)[T.3.0]':'occ_3', 
 
'C(occupation)[T.4.0]':'occ_4', 
 
'C(occupation)[T.5.0]':'occ_5', 
 
'C(occupation)[T.6.0]':'occ_6', 
 
'C(occupation_husb)[T.2.0]':'occ_husb_2', 
 
'C(occupation_husb)[T.3.0]':'occ_husb_3', 
 
'C(occupation_husb)[T.4.0]':'occ_husb_4', 
 
'C(occupation_husb)[T.5.0]':'occ_husb_5', 
 
'C(occupation_husb)[T.6.0]':'occ_husb_6'}) 
 
y = np.ravel(y) 

In [11]:
y

array([1., 1., 1., ..., 0., 0., 0.])

In [12]:
X

Intercept  occ_2  occ_3  occ_4  occ_5  occ_6  occ_husb_2  occ_husb_3  \
0           1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   
1           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
2           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
3           1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
4           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
...         ...    ...    ...    ...    ...    ...         ...         ...   
6361        1.0    0.0    0.0    1.0    0.0    0.0         0.0         1.0   
6362        1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
6363        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6364        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6365        1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   

      occ_husb_4  occ_husb_5  occ_husb_6  rate_marriage   age  yrs_married  \
0            0.0         1.0         0.0            3.0  32.0          9.0   
1            1.0         0.0         0.0            3.0  27.0         13.0   
2            0.0         1.0         0.0            4.0  22.0          2.5   
3            0.0         1.0         0.0            4.0  37.0         16.5   
4            1.0         0.0         0.0            5.0  27.0          9.0   
...          ...         ...         ...            ...   ...          ...   
6361         0.0         0.0         0.0            5.0  32.0         13.0   
6362         0.0         1.0         0.0            4.0  32.0         13.0   
6363         0.0         0.0         0.0            5.0  22.0          2.5   
6364         1.0         0.0         0.0            5.0  32.0          6.0   
6365         1.0         0.0         0.0            4.0  22.0          2.5   

      children  religious  educ  
0          3.0        3.0  17.0  
1          3.0        1.0  14.0  
2          0.0        1.0  16.0  
3          4.0        3.0  16.0  
4          1.0        1.0  14.0  
...        ...        ...   ...  
6361       2.0        3.0  17.0  
6362       1.0        1.0  16.0  
6363       0.0        2.0  14.0  
6364       1.0        3.0  14.0  
6365       0.0        2.0  16.0  

[6366 rows x 17 columns]

In [16]:
# Splitting the data
from sklearn.model_selection import train_test_split,cross_val_score

In [17]:
xtrain,xtest,ytrain,ytest = train_test_split(X.iloc[:,1:],y,test_size=0.30)

In [18]:
# Training the model
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [20]:
cross_val = cross_val_score(estimator=log,X=xtrain,y=ytrain,cv=5,verbose=1)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.6s finished


In [21]:
cross_val

array([0.72869955, 0.73176207, 0.72839506, 0.7295174 , 0.70258137])

In [22]:
log.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
# make predictions
ypred = log.predict(xtest)

In [24]:
# model evaluation
from sklearn import metrics

In [26]:
# Accuracy score
metrics.accuracy_score(ytest,ypred)

0.7172774869109948

In [25]:
metrics.confusion_matrix(ytest,ypred)

array([[1164,  126],
       [ 414,  206]], dtype=int64)

In [28]:
print(metrics.classification_report(ytest,ypred))

              precision    recall  f1-score   support

         0.0       0.74      0.90      0.81      1290
         1.0       0.62      0.33      0.43       620

    accuracy                           0.72      1910
   macro avg       0.68      0.62      0.62      1910
weighted avg       0.70      0.72      0.69      1910

